version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: john
      POSTGRES_PASSWORD: example
      POSTGRES_DB: movies
    volumes:
      - dbvolume:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080

  backend:
    image: hiteshgrw/mreviewbackend:latest
    environment:
      DB_USER: john
      DB_PASS: example
      DB: movies
      DB_HOST: db
    links:
      - db

  frontend:
    image: hiteshgrw/mreviewfrontend:lastest
    ports:
      - 80:5000
    links:
      - backend

volumes:
  dbvolume: